apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: events-website
 name: events-website
spec:
 replicas: 1
 selector:
   matchLabels:
     app: events-website
     ver: v1.0
 template:
   metadata:
     labels:
       app: events-website
       ver: v1.0
   spec:
     containers:
     - image: javyfake/events-website:v1.0
       name: events-website
       ports:
       - containerPort: 8082